export const nossoCaderninho = {
  color: {
    enamel: 'var(--nc-color-enamel, #f2f5f4)',
    plate: 'var(--nc-color-plate, #ffffff)',
    graphite: 'var(--nc-color-graphite, #202729)',
    graphiteSubdued: 'var(--nc-color-graphite-subdued, #5d6a6d)',
    rail: 'var(--nc-color-rail, #b8c3c2)',
    railSoft: 'var(--nc-color-rail-soft, #dfe6e4)',
    signalSoft: 'var(--nc-color-signal-soft, #edf2f1)',
    partnership: 'var(--nc-color-partnership, #26677a)',
    partnershipSurface: 'var(--nc-color-partnership-surface, #26677a)',
    partnershipSoft: 'var(--nc-color-partnership-soft, #e4eff1)',
    balance: 'var(--nc-color-balance, #4c7a61)',
    balanceSoft: 'var(--nc-color-balance-soft, #e8f0eb)',
    commitment: 'var(--nc-color-commitment, #b96f00)',
    commitmentSoft: 'var(--nc-color-commitment-soft, #fff1db)',
    limit: 'var(--nc-color-limit, #b44238)',
    limitSoft: 'var(--nc-color-limit-soft, #fbe9e7)',
    nav: 'var(--nc-color-nav, #10292f)',
    navHover: 'var(--nc-color-nav-hover, #183a43)',
    navText: 'var(--nc-color-nav-text, #f3f7f6)',
    navTextSubdued: 'var(--nc-color-nav-text-subdued, #b8c8c8)',
    focusOnLight: 'var(--nc-color-focus-on-light, #26677a)',
    focusOnDark: 'var(--nc-color-focus-on-dark, #58a7b8)',
  },
  font: {
    family:
      'Aptos, "Segoe UI Variable", "Segoe UI", system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
  },
  radius: {
    control: 6,
    panel: 10,
    status: 999,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  motion: {
    duration: '180ms',
    easing: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
  },
} as const;
